import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import './globals.css';
import { QueryProviders } from '@/provider';
import { Dashboard, Search } from './_components';
import Image from 'next/image';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <QueryProviders>
          <main>
            <Dashboard>
              <Image src="/images/banner-myjishoapp.png" alt="MyJisho Logo" width={530} height={125} className="mx-auto mb-3" />
              <Search />
              {children}
            </Dashboard>
          </main>
        </QueryProviders>
      </body>
    </html>
  );
}
